version: '3.8'

services:
  db:
    image: postgres:15
    container_name: finance-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance_app
    ports:
      - '5433:5432'
    volumes:
      - finance-app-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  finance-app-db-data:
